"""FastAPI application entry point.

Provides:
- ``GET  /health``       — health check
- ``POST /predict-gev``  — GEBV prediction via RR-BLUP

Swagger UI is available at ``/docs`` (auto-generated by FastAPI).
"""

import logging
from contextlib import asynccontextmanager

from fastapi import FastAPI, HTTPException

from app.inference import RRBLUPModel
from app.models import HealthResponse, PredictRequest, PredictResponse

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Model singleton — loaded once at startup
# ---------------------------------------------------------------------------
model = RRBLUPModel()


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Load the RR-BLUP model on startup, log status on shutdown."""
    model.load()
    if not model.is_loaded:
        log.warning(
            "RR-BLUP model could not be loaded. "
            "Place a valid model.joblib in app/assets/ and restart."
        )
    else:
        log.info("RR-BLUP model is ready.")
    yield
    log.info("Shutting down genomic prediction API.")


app = FastAPI(
    title="Breedi Genomic Prediction API",
    description=(
        "REST API for calculating Genomic Estimated Breeding Values (GEBV) "
        "using an RR-BLUP (Ridge Regression BLUP) model.\n\n"
        "RR-BLUP is mathematically equivalent to GBLUP and estimates additive "
        "effects of individual SNP markers.  Input genotypes are encoded as "
        "allele dosages **0, 1, or 2** (count of the alternative allele) — "
        "the standard additive coding in modern genomic pipelines."
    ),
    version="0.1.0",
    lifespan=lifespan,
)


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@app.get(
    "/health",
    response_model=HealthResponse,
    summary="Health check",
    description="Returns the service health status and whether the model is loaded.",
)
async def health() -> HealthResponse:
    if model.is_loaded:
        return HealthResponse(
            status="healthy",
            model_loaded=True,
            model_version=model.version,
        )
    return HealthResponse(
        status="unhealthy",
        model_loaded=False,
        model_version=None,
    )


@app.post(
    "/predict-gev",
    response_model=PredictResponse,
    summary="Predict GEBV for an animal",
    description=(
        "Compute the Genomic Estimated Breeding Value (GEBV) from SNP dosages.\n\n"
        "Each dosage must be **0, 1, or 2** — the number of alternative alleles "
        "at the marker locus (additive genetic model used in RR-BLUP / GBLUP)."
    ),
)
async def predict_gev(payload: PredictRequest) -> PredictResponse:
    if not model.is_loaded:
        raise HTTPException(
            status_code=503,
            detail="RR-BLUP model is not loaded. Service is unavailable.",
        )

    try:
        result = model.predict(payload.snp_dosages)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc))
    except Exception:
        log.exception("Unexpected error during prediction")
        raise HTTPException(status_code=500, detail="Internal prediction error")

    return PredictResponse(
        animal_id=payload.animal_id,
        gebv=result["gebv"],
        accuracy=result["accuracy"],
        percentile=result["percentile"],
    )
